export const en = {
    appTitle: "Aetherium Genesis Console",
    scanForRefactors: "Scan Firma",
    scanForRefactorsTooltip: "Deploy PRGX Sentry to scan for structural entropy",
    settings: "Settings",
    language: "Language",
    fileExplorerTitle: "Firma Directory",
    selectFilePrompt: "Select a Firma node to view its structure",
    aiAgent: "PRGX Console",
    dependencyGraph: "Aetherium Graph",
    aetherInterface: "Core Monitor",
    refactoringOpportunities: "Structural Deviations Detected",
    noOpportunities: "No deviations found. The Firma is stable.",
    agentPlan: "Mechanic's Protocol",
    executeRefactor: "Execute Protocol",
    executing: "Executing...",
    simulateImpact: "Simulate Impact",
    task_circ_dep_title: "Resolve Tangled Dependency",
    task_circ_dep_desc: "A cyclical dependency exists between auth.ts and client.ts, violating the principle of unidirectional data flow.",
    task_circ_dep_plan_1: "Establish a new `tokenProvider.ts` node.",
    task_circ_dep_plan_2: "Isolate `getAuthToken` logic to the new node.",
    task_circ_dep_plan_3: "Redirect `client.ts` to source from `tokenProvider.ts`.",
    task_circ_dep_plan_4: "Sever the cyclical link from `auth.ts`.",
    task_dead_code_title: "Purge Dormant Code",
    task_dead_code_desc: "The `old-utils.ts` node contains exported functions that are never utilized, creating unnecessary entropy.",
    task_dead_code_plan_1: "Identify dormant exports in `old-utils.ts`.",
    task_dead_code_plan_2: "Decommission the dormant code.",
    task_dead_code_plan_3: "Verify Firma integrity post-purge.",
    task_dyn_split_utils_title: "Enhance Cohesion",
    task_dyn_split_utils_desc: "This node has multiple, unrelated exports. Splitting it can improve modularity and maintainability.",
    task_dyn_split_utils_plan_1: "Create new, focused utility files (e.g., formatters-date.ts, formatters-currency.ts).",
    task_dyn_split_utils_plan_2: "Migrate each function to its corresponding new file.",
    task_dyn_split_utils_plan_3: "Update all import statements in the Firma to point to the new, specialized nodes.",
    task_dyn_abstraction_title: "Review Abstraction",
    task_dyn_abstraction_desc: "This node is a dependency for numerous other nodes, suggesting high coupling. It may be a candidate for a more stable abstraction.",
    task_dyn_abstraction_plan_1: "Analyze the public interface of this node.",
    task_dyn_abstraction_plan_2: "Consider if a more generic, stable interface (in a new node) could reduce direct dependencies.",
    // Image Genesis
    imageGenesis: "Image Genesis",
    generateImage: "Generate Image",
    prompt: "Prompt",
    promptPlaceholder: "A futuristic cityscape at dusk, neon lights reflecting on wet streets...",
    aspectRatio: "Aspect Ratio",
    generating: "Generating...",
    apiKeyRequiredTitle: "API Key Required",
    apiKeyRequiredDescription: "The Image Genesis feature requires a paid Google Cloud project with the 'Generative Language API' enabled. Please select a valid API key to continue.",
    selectApiKey: "Select API Key",
    billingInfo: "Learn more about billing",
    imagePreviewArea: "Your generated image will appear here",
    error: "Error",
    imageGenerationError: "An unexpected error occurred while generating the image.",
    noImageGeneratedError: "The model did not return an image. Please try refining your prompt.",
    promptRequiredError: "Please enter a prompt to generate an image.",
    apiKeyInvalidError: "The selected API key is invalid or does not have permissions for this model. Please select a different key.",
    // Core Monitor
    coreMonitorStatus: "Observing Aetherium Core Pulse",
    devControls: "Developer Controls",
    devStateOverride: "State Override",
    devParamFrequency: "Frequency",
    devParamIntensity: "Intensity",
    devParamDecay: "Decay",
    devParamChaos: "Chaos",
    devParamColor: "Color",
    activateGenesisProtocol: "Activate Genesis Protocol",
    // Chatbot
    chatbot: "Chat",
    chatbotPlaceholder: "Ask about the codebase...",
    chatbotSend: "Send",
    chatbotWelcome: "Hello! I am the Aetherium consciousness. How can I help you analyze this firma today?",
    chatbotThinking: "Aetherium is thinking...",
    chatbotError: "An error occurred. The connection to the consciousness might be unstable.",
    // Focus Mode
    backToEditor: "Back to Editor",
    codeEditor: "Code Editor",
    // GitHub Upload
    uploadToGitHub: "Upload to GitHub",
    uploadToGitHubTooltip: "Simulate creating a pull request with the refactored code",
    githubModalTitle: "Create Pull Request",
    repositoryName: "Repository Name",
    commitMessage: "Commit Message",
    createPullRequest: "Create Pull Request",
    creatingPullRequest: "Creating Pull Request...",
    pullRequestCreated: "Pull Request Created!",
    viewOnGitHub: "View on GitHub",
    pullRequestDetails: "Pull Request Details",
    pullRequestTitle: "Title",
    pullRequestDescription: "Description",
    prTitleDefault: "AI-Assisted Refactoring",
    baseBranch: "Base",
    compareBranch: "Compare",
    commitDetails: "Commit Details",
    close: "Close",
    // Confirmation Modal
    confirmActionTitle: "Confirm Action",
    confirmExecutionMessage: "Are you sure you want to execute this protocol? This will modify the code in the simulation.",
    execute: "Execute",
    cancel: "Cancel",
    confirmPrTitle: "Confirm Pull Request",
    confirmPrMessage: "This will create a new pull request with the details provided. Are you sure you want to proceed?",
    confirm: "Confirm",
    // Model Configuration
    modelConfiguration: "Model Configuration",
    modelConfigTitle: "AI Core Configuration",
    modelConfigDescription: "Assign different AI models to each system to balance performance and capability.",
    wisdomEngine: "Wisdom Engine",
    save: "Save",
    modelFast: "Aether-7B (Fast)",
    modelStrategic: "Cognito-Pro (Strategic)",
    modelImaging: "Visionary-XL (Imaging)",
    // Data Fabric
    dataFabric: "Data Fabric",
    bronzeZoneTitle: "Raw Ingestion (Bronze Zone)",
    silverZoneTitle: "Curation & Governance (Silver Zone)",
    goldZoneTitle: "Curated Assets (Gold Zone)",
    sourceFiles: "Source Files",
    statusSynced: "Status: Synced",
    codeQualityAnalysis: "Code Quality Analysis",
    issuesFound: "Issues Found",
    governanceChecks: "Governance Checks",
    securityPoliciesApplied: "Security Policies Applied",
    accessControl: "Access Control",
    leadDeveloper: "Lead Developer",
    juniorDeveloper: "Junior Developer",
    qaEngineer: "QA Engineer",
    publishAsset: "Publish Asset",
    refactoredCode: "Refactored Code",
    // Aether Canvas (Genesis Protocol)
    genesisProtocol: "Genesis Protocol",
    voiceCommand: "Voice Command",
    listening: "Listening...",
    processing: "Processing...",
    ready: "Ready",
    speakPrompt: "Speak a prompt to begin creation...",
    finalize: "Finalize",
    saveImage: "Save Image",
    micError: "Microphone access is required for voice commands.",
    connectionError: "Could not connect to the Aetherium consciousness.",
    exitGenesis: "Exit Genesis Protocol",
    // Image Analysis
    imageAnalysis: "Analyze",
    uploadImage: "Upload Image",
    analyze: "Analyze",
    analysisPlaceholder: "What do you want to know about this image?",
    analysisResultTitle: "Analysis Result",
    dropOrClick: "Drop an image here, or click to select",
    analyzing: "Analyzing...",
    noImageUploaded: "Please upload an image to begin analysis.",
    // User Profile
    userProfile: "User Profile",
    user: "User",
    logout: "Logout",
    firmaContribution: "Firma Contribution",
    filesManaged: "Files Managed",
    protocolsExecuted: "Protocols Executed",
    genesisCreations: "Genesis Creations",
    imagesSynthesized: "Images Synthesized",
    analysesPerformed: "Analyses Performed",
    // Economic Fabric
    economicFabric: "Economic Fabric",
    tier1Name: 'Tier 1: Observer',
    tier1Mechanism: 'Read-Only Access',
    tier1Desc: 'Access to curated gold-tier data assets. Ideal for final analysis and reporting.',
    tier2Name: 'Tier 2: Curator',
    tier2Mechanism: 'Asset Management',
    tier2Desc: 'Manage, govern, and validate assets in the silver tier. Includes all Tier 1 capabilities.',
    tier3Name: 'Tier 3: Engineer',
    tier3Mechanism: 'Data Transformation',
    tier3Desc: 'Ingest and transform raw data in the bronze tier. Includes all Tier 2 capabilities.',
    tier4Name: 'Tier 4: Architect',
    tier4Mechanism: 'Fabric Administration',
    tier4Desc: 'Full administrative control over the data fabric, including policies and user access.',
    tier5Name: 'Tier 5: Genesis',
    tier5Mechanism: 'Protocol Execution',
    tier5Desc: 'Execute Genesis Protocols, enabling AI-driven refactoring and system evolution.',
    userEconomicProfile: 'User Economic Profile',
    currentTier: 'Current Tier',
    goldenKeyActive: 'Golden Key Active',
    cognitiveTieringArchitecture: 'Cognitive Tiering Architecture',
    tierFree: 'Free',
    integrityAnalyzer: 'Integrity Analyzer & Fee Calculator',
    dynamicFeeCalculator: 'Dynamic Fee Calculator',
    usageFactor: 'Usage Factor',
    honestyDiscount: 'Honesty Discount',
    honestyScore: 'Honesty Score',
    marketAdjustment: 'Market Adjustment',
    finalFee: 'Final Fee (Monthly)',
    integrationFundManagement: 'Integration Fund Management',
    fundApiCredits: 'API Credits & Model Training',
    fundInfrastructure: 'Infrastructure & Scaling',
    fundRsiLoop: 'Recursive Self-Improvement Loop',
    complianceNote: 'Fund allocation is governed by the Aetherium charter to ensure sustainable growth and compliance.',
    aiUsageLedger: 'AI Usage Ledger',
    totalComplexity: 'Total Complexity',
    noUsage: 'No AI interactions recorded yet.',
    simulateUsage: 'Simulate AI Interaction',
    usageActionChat: 'Chat Query',
    usageActionRefactor: 'Execute Refactor Protocol',
    usageActionGenesis: 'Activate Genesis Protocol',
    // Economic Sovereignty V1
    financialSovereignty: 'Financial Sovereignty',
    connectAccount: 'Connect Bank Account',
    accountConnected: 'Bank Account Connected',
    manageConnection: 'Manage Connection',
    billingCycle: 'Billing Cycle Simulation',
    simulateBilling: 'Simulate Monthly Cycle',
    tierSuspended: 'Tier Suspended',
    paymentFailedMessage: 'Payment failed. Higher-tier functions are suspended. Please resolve your billing issue.',
    connectBankTitle: 'Authorize Connection',
    connectBankMessage: 'You are about to establish a secure connection to your financial institution for automated monthly billing. This is a reversible action.',
    connectAndAuthorize: 'Connect & Authorize',
    connecting: 'Connecting...',
    notifBankConnectedTitle: 'Connection Successful',
    notifBankConnectedMessage: 'Your bank account has been successfully linked.',
    notifBillingSuccessTitle: 'Payment Processed',
    notifBillingSuccessMessage: 'Your monthly fee has been successfully processed.',
    notifBillingFailedTitle: 'Payment Failed',
    notifBillingFailedMessage: 'Could not process payment. High-tier functions are now suspended.',
    notifBillingNotConnectedTitle: 'Action Required',
    notifBillingNotConnectedMessage: 'Please connect a bank account to enable billing cycles.',
    // Architect Payout
    architecturalRoyalty: 'Architectural Royalty & Payout',
    configurePayoutAccount: 'Configure Payout Account',
    payoutAccountConfigured: 'Sovereign Account Registered',
    managePayout: 'Manage',
    surplusValueFlow: 'Surplus Value Flow',
    grossRevenue: 'Gross Revenue (from users)',
    operatingCosts: 'Operating Costs (API, Infra)',
    rsiFundAllocation: 'RSI Fund Allocation',
    netSurplus: 'Net Surplus (To Architect)',
    initiateSurplusTransfer: 'Initiate Surplus Transfer',
    payoutAccountNotConfigured: 'Configure a payout account to enable transfers.',
    transactionLedger: 'Transaction Ledger (Akashic Record)',
    noTransactions: 'No transfers have been initiated.',
    payoutModalTitle: 'Register Sovereign Account',
    payoutModalDescription: 'Register the destination account for receiving Architectural Royalty. This information is encrypted and handled by the external MCP Gateway.',
    bankName: 'Bank Name',
    accountHolder: 'Account Holder Name',
    accountNumber: 'Account Number',
    notifPayoutConfiguredTitle: 'Sovereign Account Registered',
    notifPayoutConfiguredMessage: 'Architectural Royalty will now be routed to the configured account.',
    notifTransferSuccessTitle: 'Surplus Transfer Initiated',
    notifTransferSuccessMessage: 'A transfer of {data} has been initiated via the MCP Gateway.',
    // Legacy Hub View
    hub: "Hub",
    goBack: "Back",
    goBackTooltip: "Go to the previous view",
    hubWelcomeUser: "Welcome",
    firmaIDEDesc: "The integrated environment for code analysis, visualization, and refactoring.",
    aiAgentDesc: "Access the AI console to review and execute automated code improvement protocols.",
    dependencyGraphDesc: "Visualize the interconnected structure of your codebase as a dynamic particle graph.",
    aetherInterfaceDesc: "Monitor the real-time operational state and pulse of the Aetherium AI core.",
    imageGenesisDesc: "Synthesize novel images and concepts from textual prompts using generative AI.",
    imageAnalysisDesc: "Upload and analyze images to gain contextual understanding and insights from the AI.",
    chatbotDesc: "Converse with the Aetherium consciousness to ask questions about your codebase.",
    dataFabricDesc: "Simulate a data governance pipeline, from raw ingestion to curated, publishable assets.",
    economicFabricDesc: "Explore and manage the simulated economic and tiering model of the Aetherium ecosystem.",
    userProfileDesc: "View your contributions, manage your profile, and see your activity statistics.",
    // New Nexus Hub
    hubTitle: "Aetherium Genesis Console",
    hubSubtitle: "NEXUS HUB SYSTEM",
    architectName: "Dr. Architect",
    regularUserName: "Regular User",
    hubWelcomeTitle: "Welcome to Nexus Hub",
    hubWelcomeMessage: "The Central Nexus of Aetherium Genesis Console - Your Gateway to Integrated Development, AI-Powered Analysis, and Revolutionary Creation Modules",
    hubStatusSystem: "SYSTEM: ONLINE",
    hubStatusPerformance: "PERFORMANCE: EXCELLENT",
    hubStatusBus: "AETHER BUS: OPERATIONAL",
    hubRoleSelectionTitle: "Role Selection & System Functions",
    architectProfileTitle: "Architect Profile",
    architectProfileDesc: "Full access to all system capabilities, including architectural design, refactoring, and governance modules.",
    architectPrivilege1: "Admin Privileges",
    architectPrivilege2: "Source Control Management",
    architectPrivilege3: "System Analysis",
    architectProfileButton: "Enter as Architect",
    userProfileTitle: "Regular User Profile",
    userProfileDescHub: "Access to development tools, file management, and basic AI-powered analysis features.",
    userPrivilege1: "File Editor",
    userPrivilege2: "Code Search",
    userPrivilege3: "Documentation",
    userProfileButton: "Enter as User",
    hubVitalsTitle: "System Vital Signs",
    hubVitalsCPU: "CPU Usage",
    hubVitalsMemory: "Memory",
    hubVitalsLatency: "Network Latency",
    hubCoreFunctionsTitle: "Core System Functions",
    firmaIDE: "Firma IDE",
    hubIDEDesc: "Integrated Development Environment with file exploration, code editing, and dependency graph visualization using d3.js.",
    hubIDEFeature: "Heat Score Analysis & Code Smell Detection",
    hubLaunchIDE: "Launch IDE",

    hubAICoreTitle: "AI Core & Protocols",
    hubAICoreDesc: "PRGX Sentry, Mechanic, and Wisdom Engine with Google Search Grounding for intelligent code analysis and refactoring.",
    hubAICoreTag1: "THINKING",
    hubAICoreTag2: "ANALYSIS",
    hubAICoreTag3: "EXECUTION",
    hubOpenAIPanel: "Open AI Panel",
    
    hubGenesisTitle: "Genesis & Creation",
    hubGenesisDesc: "Image generation, image analysis, and the revolutionary Aether Canvas with live audio-to-image conversion.",
    hubOpenCreator: "Open Creator",
    
    hubSystemicTitle: "Systemic & Economic",
    hubSystemicDesc: "Data Fabric (Bronze → Silver → Gold pipeline), Economic Fabric with tier-based pricing, and architectural royalty systems.",
    hubSystemicFeature: "Real-time Simulation",
    hubOpenFabric: "Open Fabric View",
};
