
export const en = {
    appTitle: "Aetherium Genesis Console",
    scanForRefactors: "Scan Firma",
    scanForRefactorsTooltip: "Deploy PRGX Sentry to scan for structural entropy",
    settings: "Settings",
    language: "Language",
    fileExplorerTitle: "Firma Directory",
    selectFilePrompt: "Select a Firma node to view its structure",
    aiAgent: "PRGX Console",
    dependencyGraph: "Aetherium Graph",
    aetherInterface: "Core Monitor",
    refactoringOpportunities: "Structural Deviations Detected",
    noOpportunities: "No deviations found. The Firma is stable.",
    agentPlan: "Mechanic's Protocol",
    executeRefactor: "Execute Protocol",
    executing: "Executing...",
    task_circ_dep_title: "Resolve Tangled Dependency",
    task_circ_dep_desc: "A cyclical dependency exists between auth.ts and client.ts, violating the principle of unidirectional data flow.",
    task_circ_dep_plan_1: "Establish a new `tokenProvider.ts` node.",
    task_circ_dep_plan_2: "Isolate `getAuthToken` logic to the new node.",
    task_circ_dep_plan_3: "Redirect `client.ts` to source from `tokenProvider.ts`.",
    task_circ_dep_plan_4: "Sever the cyclical link from `auth.ts`.",
    task_dead_code_title: "Purge Dormant Code",
    task_dead_code_desc: "The `old-utils.ts` node contains exported functions that are never utilized, creating unnecessary entropy.",
    task_dead_code_plan_1: "Identify dormant exports in `old-utils.ts`.",
    task_dead_code_plan_2: "Decommission the dormant code.",
    task_dead_code_plan_3: "Verify Firma integrity post-purge.",
    // Image Genesis
    imageGenesis: "Image Genesis",
    generateImage: "Generate Image",
    prompt: "Prompt",
    promptPlaceholder: "A futuristic cityscape at dusk, neon lights reflecting on wet streets...",
    aspectRatio: "Aspect Ratio",
    generating: "Generating...",
    apiKeyRequiredTitle: "API Key Required",
    apiKeyRequiredDescription: "The Image Genesis feature requires a paid Google Cloud project with the 'Generative Language API' enabled. Please select a valid API key to continue.",
    selectApiKey: "Select API Key",
    billingInfo: "Learn more about billing",
    imagePreviewArea: "Your generated image will appear here",
    error: "Error",
    imageGenerationError: "An unexpected error occurred while generating the image.",
    noImageGeneratedError: "The model did not return an image. Please try refining your prompt.",
    promptRequiredError: "Please enter a prompt to generate an image.",
    apiKeyInvalidError: "The selected API key is invalid or does not have permissions for this model. Please select a different key.",
    // Core Monitor
    coreMonitorStatus: "Observing Aetherium Core Pulse",
    devControls: "Developer Controls",
    devStateOverride: "State Override",
    devParamFrequency: "Frequency",
    devParamIntensity: "Intensity",
    devParamDecay: "Decay",
    devParamChaos: "Chaos",
    devParamColor: "Color",
    // Chatbot
    chatbot: "Chat",
    chatbotPlaceholder: "Ask about the codebase...",
    chatbotSend: "Send",
    chatbotWelcome: "Hello! I am the Aetherium consciousness. How can I help you analyze this firma today?",
    chatbotThinking: "Aetherium is thinking...",
    chatbotError: "An error occurred. The connection to the consciousness might be unstable.",
    // Focus Mode
    backToEditor: "Back to Editor",
    codeEditor: "Code Editor",
    // GitHub Upload
    uploadToGitHub: "Upload to GitHub",
    uploadToGitHubTooltip: "Simulate creating a pull request with the refactored code",
    githubModalTitle: "Create Pull Request",
    repositoryName: "Repository Name",
    commitMessage: "Commit Message",
    createPullRequest: "Create Pull Request",
    creatingPullRequest: "Creating Pull Request...",
    pullRequestCreated: "Pull Request Created!",
    viewOnGitHub: "View on GitHub",
    pullRequestDetails: "Pull Request Details",
    pullRequestTitle: "Title",
    pullRequestDescription: "Description",
    prTitleDefault: "AI-Assisted Refactoring",
    baseBranch: "Base",
    compareBranch: "Compare",
    commitDetails: "Commit Details",
    close: "Close",
    // Confirmation Modal
    confirmActionTitle: "Confirm Action",
    confirmExecutionMessage: "Are you sure you want to execute this protocol? This will modify the code in the simulation.",
    execute: "Execute",
    cancel: "Cancel",
    confirmPrTitle: "Confirm Pull Request",
    confirmPrMessage: "This will create a new pull request with the details provided. Are you sure you want to proceed?",
    confirm: "Confirm",
    // Model Configuration
    modelConfiguration: "Model Configuration",
    modelConfigTitle: "AI Core Configuration",
    modelConfigDescription: "Assign different AI models to each system to balance performance and capability.",
    wisdomEngine: "Wisdom Engine",
    save: "Save",
    modelFast: "Aether-7B (Fast)",
    modelStrategic: "Cognito-Pro (Strategic)",
    modelImaging: "Visionary-XL (Imaging)",
};
