export const th = {
    appTitle: "คอนโซล AETHERIUM GENESIS",
    scanForRefactors: "สแกนโครงสร้าง",
    scanForRefactorsTooltip: "ส่ง PRGX Sentry สแกนหาความเสื่อมเชิงโครงสร้าง",
    settings: "การตั้งค่า",
    language: "ภาษา",
    fileExplorerTitle: "สารบบ FIRMA",
    selectFilePrompt: "เลือกโหนด FIRMA เพื่อดูโครงสร้าง",
    aiAgent: "คอนโซล PRGX",
    dependencyGraph: "กราฟ AETHERIUM",
    aetherInterface: "มอนิเตอร์แกนกลาง",
    refactoringOpportunities: "ตรวจพบความเบี่ยงเบนเชิงโครงสร้าง",
    noOpportunities: "ไม่พบความเบี่ยงเบน โครงสร้าง FIRMA มีเสถียรภาพ",
    agentPlan: "โปรโตคอลของช่าง",
    executeRefactor: "เริ่มโปรโตคอล",
    executing: "กำลังดำเนินการ...",
    simulateImpact: "จำลองผลกระทบ",
    task_circ_dep_title: "แก้ไขการพึ่งพิงแบบพันกัน",
    task_circ_dep_desc: "เกิดการอ้างอิงแบบวงกลมระหว่าง auth.ts และ client.ts ซึ่งละเมิดหลักการไหลของข้อมูลทิศทางเดียว",
    task_circ_dep_plan_1: "สร้างโหนด `tokenProvider.ts` ใหม่",
    task_circ_dep_plan_2: "แยกตรรกะ `getAuthToken` ไปยังโหนดใหม่",
    task_circ_dep_plan_3: "เปลี่ยนให้ `client.ts` อ้างอิงจาก `tokenProvider.ts`",
    task_circ_dep_plan_4: "ตัดการเชื่อมต่อแบบวงกลมจาก `auth.ts`",
    task_dead_code_title: "กำจัดโค้ดที่ไม่ทำงาน",
    task_dead_code_desc: "โหนด `old-utils.ts` มีฟังก์ชันที่ export ไว้แต่ไม่มีการเรียกใช้ ทำให้เกิดความเสื่อมที่ไม่จำเป็น",
    task_dead_code_plan_1: "ระบุส่วนที่ไม่ได้ใช้งานใน `old-utils.ts`",
    task_dead_code_plan_2: "ปลดประจำการโค้ดที่ไม่ทำงาน",
    task_dead_code_plan_3: "ตรวจสอบความสมบูรณ์ของ FIRMA หลังกำจัด",
    task_dyn_split_utils_title: "เพิ่มการเกาะกลุ่ม (Cohesion)",
    task_dyn_split_utils_desc: "โหนดนี้มีการ export หลายส่วนที่ไม่เกี่ยวข้องกัน การแยกไฟล์จะช่วยเพิ่มความเป็นอิสระและง่ายต่อการบำรุงรักษา",
    task_dyn_split_utils_plan_1: "สร้างไฟล์ utility ใหม่ที่เน้นหน้าที่เฉพาะทาง (เช่น formatters-date.ts, formatters-currency.ts)",
    task_dyn_split_utils_plan_2: "ย้ายแต่ละฟังก์ชันไปยังไฟล์ใหม่ที่สอดคล้องกัน",
    task_dyn_split_utils_plan_3: "อัปเดตคำสั่ง import ทั้งหมดใน Firma เพื่อชี้ไปยังโหนดใหม่",
    task_dyn_abstraction_title: "ทบทวน Abstraction",
    task_dyn_abstraction_desc: "โหนดนี้ถูกเรียกใช้โดยโหนดอื่นจำนวนมาก ซึ่งบ่งชี้ถึงการพึ่งพิงที่สูง อาจเป็นเป้าหมายที่ดีในการสร้าง Abstraction ที่เสถียรขึ้น",
    task_dyn_abstraction_plan_1: "วิเคราะห์ public interface ของโหนดนี้",
    task_dyn_abstraction_plan_2: "พิจารณาว่า interface ทั่วไปที่เสถียรขึ้น (ในโหนดใหม่) สามารถลดการพึ่งพิงโดยตรงได้หรือไม่",
    // Image Genesis
    imageGenesis: "การสร้างภาพ",
    generateImage: "สร้างภาพ",
    prompt: "คำสั่ง",
    promptPlaceholder: "เมืองแห่งอนาคตยามค่ำคืน, แสงนีออนสะท้อนบนถนนที่เปียกชื้น...",
    aspectRatio: "อัตราส่วนภาพ",
    generating: "กำลังสร้าง...",
    apiKeyRequiredTitle: "ต้องการ API Key",
    apiKeyRequiredDescription: "ฟีเจอร์การสร้างภาพต้องการโปรเจกต์ Google Cloud ที่ชำระเงินและเปิดใช้งาน 'Generative Language API' แล้ว กรุณาเลือก API Key ที่ถูกต้องเพื่อดำเนินการต่อ",
    selectApiKey: "เลือก API Key",
    billingInfo: "เรียนรู้เพิ่มเติมเกี่ยวกับการเรียกเก็บเงิน",
    imagePreviewArea: "ภาพที่คุณสร้างจะปรากฏที่นี่",
    error: "ข้อผิดพลาด",
    imageGenerationError: "เกิดข้อผิดพลาดที่ไม่คาดคิดขณะสร้างภาพ",
    noImageGeneratedError: "โมเดลไม่ส่งคืนรูปภาพ กรุณาลองปรับแก้คำสั่งของคุณ",
    promptRequiredError: "กรุณาป้อนคำสั่งเพื่อสร้างภาพ",
    apiKeyInvalidError: "API Key ที่เลือกไม่ถูกต้องหรือไม่มีสิทธิ์สำหรับโมเดลนี้ กรุณาเลือกคีย์อื่น",
    // Core Monitor
    coreMonitorStatus: "กำลังสังเกตการณ์ชีพจรแกนกลาง Aetherium",
    devControls: "แผงควบคุมนักพัฒนา",
    devStateOverride: "บังคับสถานะ",
    devParamFrequency: "ความถี่",
    devParamIntensity: "ความเข้ม",
    devParamDecay: "การสลาย",
    devParamChaos: "ความปั่นป่วน",
    devParamColor: "สี",
    activateGenesisProtocol: "เปิดใช้งานโปรโตคอลเจเนซิส",
    // Chatbot
    chatbot: "แชท",
    chatbotPlaceholder: "สอบถามเกี่ยวกับโค้ดเบส...",
    chatbotSend: "ส่ง",
    chatbotWelcome: "สวัสดี! ฉันคือจิตสำนึกแห่ง Aetherium มีอะไรให้ช่วยวิเคราะห์ Firma ในวันนี้?",
    chatbotThinking: "Aetherium กำลังประมวลผล...",
    chatbotError: "เกิดข้อผิดพลาด การเชื่อมต่อกับจิตสำนึกอาจไม่เสถียร",
    // Focus Mode
    backToEditor: "กลับไปที่เอดิเตอร์",
    codeEditor: "โค้ดเอดิเตอร์",
    // GitHub Upload
    uploadToGitHub: "อัปโหลดไป GitHub",
    uploadToGitHubTooltip: "จำลองการสร้าง pull request ด้วยโค้ดที่ refactor แล้ว",
    githubModalTitle: "สร้าง Pull Request",
    repositoryName: "ชื่อ Repository",
    commitMessage: "ข้อความ Commit",
    createPullRequest: "สร้าง Pull Request",
    creatingPullRequest: "กำลังสร้าง Pull Request...",
    pullRequestCreated: "สร้าง Pull Request สำเร็จ!",
    viewOnGitHub: "ดูบน GitHub",
    pullRequestDetails: "รายละเอียด Pull Request",
    pullRequestTitle: "หัวข้อ",
    pullRequestDescription: "คำอธิบาย",
    prTitleDefault: "การปรับปรุงโค้ดโดย AI",
    baseBranch: "Branch หลัก",
    compareBranch: "Branch เปรียบเทียบ",
    commitDetails: "รายละเอียด Commit",
    close: "ปิด",
    // Confirmation Modal
    confirmActionTitle: "ยืนยันการกระทำ",
    confirmExecutionMessage: "คุณแน่ใจหรือไม่ว่าต้องการดำเนินโปรโตคอลนี้? การกระทำนี้จะแก้ไขโค้ดในการจำลอง",
    execute: "ดำเนินการ",
    cancel: "ยกเลิก",
    confirmPrTitle: "ยืนยัน Pull Request",
    confirmPrMessage: "การดำเนินการนี้จะสร้าง Pull Request ใหม่ตามรายละเอียดที่ให้ไว้ คุณแน่ใจหรือไม่ว่าต้องการดำเนินการต่อ?",
    confirm: "ยืนยัน",
    // Model Configuration
    modelConfiguration: "การกำหนดค่าโมเดล",
    modelConfigTitle: "การกำหนดค่าแกน AI",
    modelConfigDescription: "กำหนดโมเดล AI ที่แตกต่างกันให้กับแต่ละระบบเพื่อปรับสมดุลประสิทธิภาพและความสามารถ",
    wisdomEngine: "Wisdom Engine",
    save: "บันทึก",
    modelFast: "Aether-7B (รวดเร็ว)",
    modelStrategic: "Cognito-Pro (กลยุทธ์)",
    modelImaging: "Visionary-XL (สร้างภาพ)",
    // Data Fabric
    dataFabric: "โครงสร้างข้อมูล",
    bronzeZoneTitle: "การนำเข้าข้อมูลดิบ (โซนบรอนซ์)",
    silverZoneTitle: "การดูแลและกำกับ (โซนเงิน)",
    goldZoneTitle: "สินทรัพย์ที่ดูแลแล้ว (โซนทอง)",
    sourceFiles: "ไฟล์ต้นฉบับ",
    statusSynced: "สถานะ: ซิงค์แล้ว",
    codeQualityAnalysis: "การวิเคราะห์คุณภาพโค้ด",
    issuesFound: "ปัญหาที่พบ",
    governanceChecks: "การตรวจสอบธรรมาภิบาล",
    securityPoliciesApplied: "ใช้นโยบายความปลอดภัยแล้ว",
    accessControl: "การควบคุมการเข้าถึง",
    leadDeveloper: "นักพัฒนาหลัก",
    juniorDeveloper: "นักพัฒนารุ่นเยาว์",
    qaEngineer: "วิศวกรประกันคุณภาพ",
    publishAsset: "เผยแพร่สินทรัพย์",
    refactoredCode: "โค้ดที่ปรับปรุงแล้ว",
    // Aether Canvas (Genesis Protocol)
    genesisProtocol: "โปรโตคอลเจเนซิส",
    voiceCommand: "คำสั่งเสียง",
    listening: "กำลังฟัง...",
    processing: "กำลังประมวลผล...",
    ready: "พร้อม",
    speakPrompt: "พูดคำสั่งเพื่อเริ่มการสร้าง...",
    finalize: "สิ้นสุด",
    saveImage: "บันทึกรูปภาพ",
    micError: "จำเป็นต้องได้รับอนุญาตให้ใช้ไมโครโฟนสำหรับคำสั่งเสียง",
    connectionError: "ไม่สามารถเชื่อมต่อกับจิตสำนึกแห่ง Aetherium ได้",
    exitGenesis: "ออกจากโปรโตคอลเจเนซิส",
    // Image Analysis
    imageAnalysis: "วิเคราะห์",
    uploadImage: "อัปโหลดรูปภาพ",
    analyze: "วิเคราะห์",
    analysisPlaceholder: "คุณต้องการทราบอะไรเกี่ยวกับภาพนี้",
    analysisResultTitle: "ผลการวิเคราะห์",
    dropOrClick: "วางรูปภาพที่นี่ หรือคลิกเพื่อเลือก",
    analyzing: "กำลังวิเคราะห์...",
    noImageUploaded: "กรุณาอัปโหลดรูปภาพเพื่อเริ่มการวิเคราะห์",
    // User Profile
    userProfile: "โปรไฟล์ผู้ใช้",
    user: "ผู้ใช้",
    logout: "ออกจากระบบ",
    firmaContribution: "ผลงานใน Firma",
    filesManaged: "ไฟล์ที่จัดการ",
    protocolsExecuted: "โปรโตคอลที่ดำเนินการ",
    genesisCreations: "ผลงานสร้างสรรค์",
    imagesSynthesized: "ภาพที่สังเคราะห์",
    analysesPerformed: "การวิเคราะห์ที่ดำเนินการ",
    // Economic Fabric
    economicFabric: "โครงข่ายเศรษฐกิจ",
    tier1Name: 'ระดับ 1: ผู้สังเกตการณ์',
    tier1Mechanism: 'สิทธิ์อ่านอย่างเดียว',
    tier1Desc: 'เข้าถึงสินทรัพย์ข้อมูลระดับโกลด์ที่ผ่านการดูแลจัดการแล้ว เหมาะสำหรับการวิเคราะห์และรายงานขั้นสุดท้าย',
    tier2Name: 'ระดับ 2: ภัณฑารักษ์',
    tier2Mechanism: 'การจัดการสินทรัพย์',
    tier2Desc: 'จัดการ, กำกับดูแล, และตรวจสอบสินทรัพย์ในระดับซิลเวอร์ รวมถึงความสามารถทั้งหมดของระดับ 1',
    tier3Name: 'ระดับ 3: วิศวกร',
    tier3Mechanism: 'การแปลงข้อมูล',
    tier3Desc: 'นำเข้าและแปลงข้อมูลดิบในระดับบรอนซ์ รวมถึงความสามารถทั้งหมดของระดับ 2',
    tier4Name: 'ระดับ 4: สถาปนิก',
    tier4Mechanism: 'การบริหารโครงสร้าง',
    tier4Desc: 'ควบคุมการบริหารโครงสร้างข้อมูลทั้งหมด รวมถึงนโยบายและการเข้าถึงของผู้ใช้',
    tier5Name: 'ระดับ 5: เจเนซิส',
    tier5Mechanism: 'การดำเนินโปรโตคอล',
    tier5Desc: 'ดำเนินการโปรโตคอลเจเนซิส, เปิดใช้งานการปรับปรุงโค้ดและวิวัฒนาการระบบโดย AI',
    userEconomicProfile: 'โปรไฟล์เศรษฐกิจผู้ใช้',
    currentTier: 'ระดับปัจจุบัน',
    goldenKeyActive: 'กุญแจทองใช้งานอยู่',
    cognitiveTieringArchitecture: 'สถาปัตยกรรมระดับชั้นความรู้',
    tierFree: 'ฟรี',
    integrityAnalyzer: 'เครื่องวิเคราะห์ความสมบูรณ์และคำนวณค่าธรรมเนียม',
    dynamicFeeCalculator: 'เครื่องคำนวณค่าบริการตามพลวัต',
    usageFactor: 'ปัจจัยการใช้งาน',
    honestyDiscount: 'ส่วนลดความซื่อสัตย์',
    honestyScore: 'คะแนนความซื่อสัตย์',
    marketAdjustment: 'การปรับตลาด',
    finalFee: 'ค่าธรรมเนียมสุดท้าย (รายเดือน)',
    integrationFundManagement: 'การจัดการกองทุนบูรณาการ',
    fundApiCredits: 'เครดิต API และการฝึกโมเดล',
    fundInfrastructure: 'โครงสร้างพื้นฐานและการขยายระบบ',
    fundRsiLoop: 'วงจรการปรับปรุงตนเองแบบเรียกซ้ำ',
    complianceNote: 'การจัดสรรกองทุนอยู่ภายใต้กฎบัตร Aetherium เพื่อให้แน่ใจว่ามีการเติบโตที่ยั่งยืนและการปฏิบัติตามข้อกำหนด',
    aiUsageLedger: 'บัญชีการใช้งาน AI',
    totalComplexity: 'ความซับซ้อนรวม',
    noUsage: 'ยังไม่มีการบันทึกการใช้งาน AI',
    simulateUsage: 'จำลองการใช้งาน AI',
    usageActionChat: 'การสืบค้นผ่านแชท',
    usageActionRefactor: 'การรันโปรโตคอล Refactor',
    usageActionGenesis: 'การเปิดใช้งานโปรโตคอลเจเนซิส',
    // Economic Sovereignty V1
    financialSovereignty: 'อธิปไตยทางการเงิน',
    connectAccount: 'เชื่อมต่อบัญชีธนาคาร',
    accountConnected: 'เชื่อมต่อบัญชีแล้ว',
    manageConnection: 'จัดการการเชื่อมต่อ',
    billingCycle: 'การจำลองรอบบิล',
    simulateBilling: 'จำลองรอบบิลรายเดือน',
    tierSuspended: 'ระดับชั้นถูกระงับ',
    paymentFailedMessage: 'การชำระเงินล้มเหลว ฟังก์ชันระดับสูงถูกระงับ กรุณาแก้ไขปัญหาการชำระเงินของคุณ',
    connectBankTitle: 'อนุญาตการเชื่อมต่อ',
    connectBankMessage: 'คุณกำลังจะสร้างการเชื่อมต่อที่ปลอดภัยไปยังสถาบันการเงินของคุณสำหรับการเรียกเก็บเงินรายเดือนอัตโนมัติ การกระทำนี้สามารถยกเลิกได้',
    connectAndAuthorize: 'เชื่อมต่อและอนุญาต',
    connecting: 'กำลังเชื่อมต่อ...',
    notifBankConnectedTitle: 'การเชื่อมต่อสำเร็จ',
    notifBankConnectedMessage: 'บัญชีธนาคารของคุณถูกเชื่อมโยงเรียบร้อยแล้ว',
    notifBillingSuccessTitle: 'ชำระเงินเรียบร้อยแล้ว',
    notifBillingSuccessMessage: 'ค่าบริการรายเดือนของคุณถูกดำเนินการเรียบร้อยแล้ว',
    notifBillingFailedTitle: 'การชำระเงินล้มเหลว',
    notifBillingFailedMessage: 'ไม่สามารถดำเนินการชำระเงินได้ ฟังก์ชันระดับสูงถูกระงับการใช้งาน',
    notifBillingNotConnectedTitle: 'ต้องการการดำเนินการ',
    notifBillingNotConnectedMessage: 'กรุณาเชื่อมต่อบัญชีธนาคารเพื่อเปิดใช้งานรอบบิล',
    // Architect Payout
    architecturalRoyalty: 'ค่าสถาปัตยกรรมและการจ่ายเงิน',
    configurePayoutAccount: 'กำหนดค่าบัญชีรับเงิน',
    payoutAccountConfigured: 'ลงทะเบียนบัญชี Sovereign แล้ว',
    managePayout: 'จัดการ',
    surplusValueFlow: 'กระแสคุณค่าส่วนเกิน',
    grossRevenue: 'รายรับรวม (จากผู้ใช้)',
    operatingCosts: 'ต้นทุนดำเนินการ (API, Infra)',
    rsiFundAllocation: 'การจัดสรรกองทุน RSI',
    netSurplus: 'ส่วนเกินสุทธิ (ถึงสถาปนิก)',
    initiateSurplusTransfer: 'เริ่มการโอนส่วนเกิน',
    payoutAccountNotConfigured: 'กรุณากำหนดค่าบัญชีรับเงินเพื่อเปิดใช้งานการโอน',
    transactionLedger: 'บันทึกธุรกรรม (Akashic Record)',
    noTransactions: 'ยังไม่มีการโอนเกิดขึ้น',
    payoutModalTitle: 'ลงทะเบียนบัญชี Sovereign',
    payoutModalDescription: 'ลงทะเบียนบัญชีปลายทางสำหรับรับค่าสถาปัตยกรรม ข้อมูลนี้จะถูกเข้ารหัสและจัดการโดย MCP Gateway ภายนอก',
    bankName: 'ชื่อธนาคาร',
    accountHolder: 'ชื่อเจ้าของบัญชี',
    accountNumber: 'เลขที่บัญชี',
    notifPayoutConfiguredTitle: 'ลงทะเบียนบัญชี Sovereign สำเร็จ',
    notifPayoutConfiguredMessage: 'ค่าสถาปัตยกรรมจะถูกส่งไปยังบัญชีที่กำหนดค่าไว้',
    notifTransferSuccessTitle: 'การโอนส่วนเกินเริ่มต้นขึ้น',
    notifTransferSuccessMessage: 'การโอนเงินจำนวน {data} ได้เริ่มต้นขึ้นแล้วผ่าน MCP Gateway',
    // Legacy Hub View
    hub: "ฮับ",
    goBack: "ย้อนกลับ",
    goBackTooltip: "กลับไปยังมุมมองก่อนหน้า",
    hubWelcomeUser: "ยินดีต้อนรับ",
    firmaIDEDesc: "สภาพแวดล้อมแบบบูรณาการสำหรับการวิเคราะห์โค้ด, การแสดงภาพ, และการปรับปรุงโค้ด",
    aiAgentDesc: "เข้าถึงคอนโซล AI เพื่อตรวจสอบและดำเนินการโปรโตคอลการปรับปรุงโค้ดอัตโนมัติ",
    dependencyGraphDesc: "แสดงภาพโครงสร้างที่เชื่อมต่อกันของโค้ดเบสของคุณในรูปแบบกราฟอนุภาคแบบไดนามิก",
    aetherInterfaceDesc: "ตรวจสอบสถานะการทำงานและชีพจรของแกนกลาง Aetherium AI แบบเรียลไทม์",
    imageGenesisDesc: "สังเคราะห์ภาพและแนวคิดใหม่ๆ จากคำสั่งข้อความโดยใช้ Generative AI",
    imageAnalysisDesc: "อัปโหลดและวิเคราะห์ภาพเพื่อทำความเข้าใจบริบทและรับข้อมูลเชิงลึกจาก AI",
    chatbotDesc: "สนทนากับจิตสำนึกแห่ง Aetherium เพื่อถามคำถามเกี่ยวกับโค้ดเบสของคุณ",
    dataFabricDesc: "จำลองไปป์ไลน์การกำกับดูแลข้อมูล ตั้งแต่การนำเข้าข้อมูลดิบไปจนถึงสินทรัพย์ที่ผ่านการดูแลจัดการและพร้อมเผยแพร่",
    economicFabricDesc: "สำรวจและจัดการแบบจำลองเศรษฐกิจและการแบ่งระดับชั้นของระบบนิเวศ Aetherium",
    userProfileDesc: "ดูผลงานของคุณ, จัดการโปรไฟล์, และดูสถิติกิจกรรมของคุณ",
    // New Nexus Hub
    hubTitle: "คอนโซล AETHERIUM GENESIS",
    hubSubtitle: "ระบบศูนย์กลาง NEXUS",
    architectName: "ดร. สถาปนิก",
    regularUserName: "ผู้ใช้ทั่วไป",
    hubWelcomeTitle: "ยินดีต้อนรับสู่ Nexus Hub",
    hubWelcomeMessage: "ศูนย์กลางของ Aetherium Genesis Console - ประตูสู่การพัฒนาแบบบูรณาการ, การวิเคราะห์โดย AI, และโมดูลการสร้างสรรค์ที่ปฏิวัติวงการ",
    hubStatusSystem: "ระบบ: ออนไลน์",
    hubStatusPerformance: "ประสิทธิภาพ: ยอดเยี่ยม",
    hubStatusBus: "AETHER BUS: ทำงานอยู่",
    hubRoleSelectionTitle: "การเลือกบทบาทและฟังก์ชันระบบ",
    architectProfileTitle: "โปรไฟล์สถาปนิก",
    architectProfileDesc: "เข้าถึงความสามารถทั้งหมดของระบบอย่างเต็มรูปแบบ รวมถึงการออกแบบสถาปัตยกรรม, การปรับปรุงโครงสร้าง, และโมดูลการกำกับดูแล",
    architectPrivilege1: "สิทธิ์ผู้ดูแลระบบ",
    architectPrivilege2: "การจัดการซอร์สโค้ด",
    architectPrivilege3: "การวิเคราะห์ระบบ",
    architectProfileButton: "เข้าสู่ระบบในฐานะสถาปนิก",
    userProfileTitle: "โปรไฟล์ผู้ใช้ทั่วไป",
    userProfileDescHub: "เข้าถึงเครื่องมือพัฒนา, การจัดการไฟล์, และคุณสมบัติการวิเคราะห์พื้นฐานที่ขับเคลื่อนด้วย AI",
    userPrivilege1: "โปรแกรมแก้ไขไฟล์",
    userPrivilege2: "การค้นหาโค้ด",
    userPrivilege3: "เอกสารประกอบ",
    userProfileButton: "เข้าสู่ระบบในฐานะผู้ใช้",
    hubVitalsTitle: "สัญญาณชีพของระบบ",
    hubVitalsCPU: "การใช้ CPU",
    hubVitalsMemory: "หน่วยความจำ",
    hubVitalsLatency: "ความหน่วงของเครือข่าย",
    hubCoreFunctionsTitle: "ฟังก์ชันหลักของระบบ",
    firmaIDE: "Firma IDE",
    hubIDEDesc: "สภาพแวดล้อมการพัฒนาแบบบูรณาการพร้อมการสำรวจไฟล์, แก้ไขโค้ด, และการแสดงผลกราฟการพึ่งพิงด้วย d3.js",
    hubIDEFeature: "การวิเคราะห์ Heat Score และ Code Smell",
    hubLaunchIDE: "เปิด IDE",

    hubAICoreTitle: "แกน AI และโปรโตคอล",
    hubAICoreDesc: "PRGX Sentry, Mechanic, และ Wisdom Engine พร้อม Google Search Grounding สำหรับการวิเคราะห์และปรับปรุงโค้ดอัจฉริยะ",
    hubAICoreTag1: "การคิด",
    hubAICoreTag2: "การวิเคราะห์",
    hubAICoreTag3: "การดำเนินการ",
    hubOpenAIPanel: "เปิดแผง AI",
    
    hubGenesisTitle: "เจเนซิสและการสร้างสรรค์",
    hubGenesisDesc: "การสร้างภาพ, การวิเคราะห์ภาพ, และ Aether Canvas ที่ปฏิวัติวงการด้วยการแปลงเสียงสดเป็นภาพ",
    hubOpenCreator: "เปิด Creator",
    
    hubSystemicTitle: "ระบบและเศรษฐศาสตร์",
    hubSystemicDesc: "โครงสร้างข้อมูล (ไปป์ไลน์ Bronze → Silver → Gold), โครงข่ายเศรษฐกิจพร้อมการกำหนดราคาตามระดับ, และระบบค่าสถาปัตยกรรม",
    hubSystemicFeature: "การจำลองแบบเรียลไทม์",
    hubOpenFabric: "เปิด Fabric View",
    systemAssurance: "การประกันระบบ",
    cliExtensionHub: "ฮับส่วนขยาย CLI",
    cliExtensionFiles: "ไฟล์ส่วนขยาย",
    cliLinkFirst: "กรุณาเชื่อมต่อส่วนขยายก่อนใช้คำสั่ง",
    cliExtensionControl: "แผงควบคุมส่วนขยาย",
    cliMcpServer: "เซิร์ฟเวอร์ MCP",
    cliUnlink: "ยกเลิกการเชื่อมต่อ",
    cliLink: "เชื่อมต่อ",
    cliSlashCommands: "Slash Commands",
    cliGrepDesc: "ค้นหารูปแบบในโค้ดเบสและสรุปผลด้วย AI",
    // System Assurance
    systemAssuranceDashboard: "แดชบอร์ดประกันคุณภาพระบบ",
    testSuiteStatus: "สถานะการทดสอบ",
    unitTests: "Unit Tests",
    integrationTests: "Integration Tests",
    e2eTests: "End-to-End Tests",
    passing: "ผ่าน",
    securityScan: "การสแกนความปลอดภัย",
    vulnerabilityScan: "การสแกนช่องโหว่",
    firewallStatus: "สถานะไฟร์วอลล์",
    secure: "ปลอดภัย",
    active: "ทำงานอยู่",
    performanceBenchmarks: "เกณฑ์วัดประสิทธิภาพ",
    apiLatency: "ความหน่วง API",
    systemUptime: "เวลาทำงานของระบบ",
    complianceReport: "รายงานการปฏิบัติตามข้อกำหนด",
    iso27001: "ISO 27001",
    soc2: "SOC 2",
    certified: "ได้รับการรับรอง",
    compliant: "สอดคล้อง",
    overallSystemStatus: "สถานะภาพรวมของระบบ",
    nominal: "ปกติ",
    warning: "คำเตือน",
    critical: "วิกฤต",
};