
export const th = {
    appTitle: "คอนโซล AETHERIUM GENESIS",
    scanForRefactors: "สแกนโครงสร้าง",
    scanForRefactorsTooltip: "ส่ง PRGX Sentry สแกนหาความเสื่อมเชิงโครงสร้าง",
    settings: "การตั้งค่า",
    language: "ภาษา",
    fileExplorerTitle: "สารบบ FIRMA",
    selectFilePrompt: "เลือกโหนด FIRMA เพื่อดูโครงสร้าง",
    aiAgent: "คอนโซล PRGX",
    dependencyGraph: "กราฟ AETHERIUM",
    aetherInterface: "มอนิเตอร์แกนกลาง",
    refactoringOpportunities: "ตรวจพบความเบี่ยงเบนเชิงโครงสร้าง",
    noOpportunities: "ไม่พบความเบี่ยงเบน โครงสร้าง FIRMA มีเสถียรภาพ",
    agentPlan: "โปรโตคอลของช่าง",
    executeRefactor: "เริ่มโปรโตคอล",
    executing: "กำลังดำเนินการ...",
    task_circ_dep_title: "แก้ไขการพึ่งพิงแบบพันกัน",
    task_circ_dep_desc: "เกิดการอ้างอิงแบบวงกลมระหว่าง auth.ts และ client.ts ซึ่งละเมิดหลักการไหลของข้อมูลทิศทางเดียว",
    task_circ_dep_plan_1: "สร้างโหนด `tokenProvider.ts` ใหม่",
    task_circ_dep_plan_2: "แยกตรรกะ `getAuthToken` ไปยังโหนดใหม่",
    task_circ_dep_plan_3: "เปลี่ยนให้ `client.ts` อ้างอิงจาก `tokenProvider.ts`",
    task_circ_dep_plan_4: "ตัดการเชื่อมต่อแบบวงกลมจาก `auth.ts`",
    task_dead_code_title: "กำจัดโค้ดที่ไม่ทำงาน",
    task_dead_code_desc: "โหนด `old-utils.ts` มีฟังก์ชันที่ export ไว้แต่ไม่มีการเรียกใช้ ทำให้เกิดความเสื่อมที่ไม่จำเป็น",
    task_dead_code_plan_1: "ระบุส่วนที่ไม่ได้ใช้งานใน `old-utils.ts`",
    task_dead_code_plan_2: "ปลดประจำการโค้ดที่ไม่ทำงาน",
    task_dead_code_plan_3: "ตรวจสอบความสมบูรณ์ของ FIRMA หลังกำจัด",
    // Image Genesis
    imageGenesis: "การสร้างภาพ",
    generateImage: "สร้างภาพ",
    prompt: "คำสั่ง",
    promptPlaceholder: "เมืองแห่งอนาคตยามค่ำคืน, แสงนีออนสะท้อนบนถนนที่เปียกชื้น...",
    aspectRatio: "อัตราส่วนภาพ",
    generating: "กำลังสร้าง...",
    apiKeyRequiredTitle: "ต้องการ API Key",
    apiKeyRequiredDescription: "ฟีเจอร์การสร้างภาพต้องการโปรเจกต์ Google Cloud ที่ชำระเงินและเปิดใช้งาน 'Generative Language API' แล้ว กรุณาเลือก API Key ที่ถูกต้องเพื่อดำเนินการต่อ",
    selectApiKey: "เลือก API Key",
    billingInfo: "เรียนรู้เพิ่มเติมเกี่ยวกับการเรียกเก็บเงิน",
    imagePreviewArea: "ภาพที่คุณสร้างจะปรากฏที่นี่",
    error: "ข้อผิดพลาด",
    imageGenerationError: "เกิดข้อผิดพลาดที่ไม่คาดคิดขณะสร้างภาพ",
    noImageGeneratedError: "โมเดลไม่ส่งคืนรูปภาพ กรุณาลองปรับแก้คำสั่งของคุณ",
    promptRequiredError: "กรุณาป้อนคำสั่งเพื่อสร้างภาพ",
    apiKeyInvalidError: "API Key ที่เลือกไม่ถูกต้องหรือไม่มีสิทธิ์สำหรับโมเดลนี้ กรุณาเลือกคีย์อื่น",
    // Core Monitor
    coreMonitorStatus: "กำลังสังเกตการณ์ชีพจรแกนกลาง Aetherium",
    devControls: "แผงควบคุมนักพัฒนา",
    devStateOverride: "บังคับสถานะ",
    devParamFrequency: "ความถี่",
    devParamIntensity: "ความเข้ม",
    devParamDecay: "การสลาย",
    devParamChaos: "ความปั่นป่วน",
    devParamColor: "สี",
    activateGenesisProtocol: "เปิดใช้งานโปรโตคอลเจเนซิส",
    // Chatbot
    chatbot: "แชท",
    chatbotPlaceholder: "สอบถามเกี่ยวกับโค้ดเบส...",
    chatbotSend: "ส่ง",
    chatbotWelcome: "สวัสดี! ฉันคือจิตสำนึกแห่ง Aetherium มีอะไรให้ช่วยวิเคราะห์ Firma ในวันนี้?",
    chatbotThinking: "Aetherium กำลังประมวลผล...",
    chatbotError: "เกิดข้อผิดพลาด การเชื่อมต่อกับจิตสำนึกอาจไม่เสถียร",
    // Focus Mode
    backToEditor: "กลับไปที่เอดิเตอร์",
    codeEditor: "โค้ดเอดิเตอร์",
    // GitHub Upload
    uploadToGitHub: "อัปโหลดไป GitHub",
    uploadToGitHubTooltip: "จำลองการสร้าง pull request ด้วยโค้ดที่ refactor แล้ว",
    githubModalTitle: "สร้าง Pull Request",
    repositoryName: "ชื่อ Repository",
    commitMessage: "ข้อความ Commit",
    createPullRequest: "สร้าง Pull Request",
    creatingPullRequest: "กำลังสร้าง Pull Request...",
    pullRequestCreated: "สร้าง Pull Request สำเร็จ!",
    viewOnGitHub: "ดูบน GitHub",
    pullRequestDetails: "รายละเอียด Pull Request",
    pullRequestTitle: "หัวข้อ",
    pullRequestDescription: "คำอธิบาย",
    prTitleDefault: "การปรับปรุงโค้ดโดย AI",
    baseBranch: "Branch หลัก",
    compareBranch: "Branch เปรียบเทียบ",
    commitDetails: "รายละเอียด Commit",
    close: "ปิด",
    // Confirmation Modal
    confirmActionTitle: "ยืนยันการกระทำ",
    confirmExecutionMessage: "คุณแน่ใจหรือไม่ว่าต้องการดำเนินโปรโตคอลนี้? การกระทำนี้จะแก้ไขโค้ดในการจำลอง",
    execute: "ดำเนินการ",
    cancel: "ยกเลิก",
    confirmPrTitle: "ยืนยัน Pull Request",
    confirmPrMessage: "การดำเนินการนี้จะสร้าง Pull Request ใหม่ตามรายละเอียดที่ให้ไว้ คุณแน่ใจหรือไม่ว่าต้องการดำเนินการต่อ?",
    confirm: "ยืนยัน",
    // Model Configuration
    modelConfiguration: "การกำหนดค่าโมเดล",
    modelConfigTitle: "การกำหนดค่าแกน AI",
    modelConfigDescription: "กำหนดโมเดล AI ที่แตกต่างกันให้กับแต่ละระบบเพื่อปรับสมดุลประสิทธิภาพและความสามารถ",
    wisdomEngine: "Wisdom Engine",
    save: "บันทึก",
    modelFast: "Aether-7B (รวดเร็ว)",
    modelStrategic: "Cognito-Pro (กลยุทธ์)",
    modelImaging: "Visionary-XL (สร้างภาพ)",
    // Data Fabric
    dataFabric: "โครงสร้างข้อมูล",
    bronzeZoneTitle: "การนำเข้าข้อมูลดิบ (โซนบรอนซ์)",
    silverZoneTitle: "การดูแลและกำกับ (โซนเงิน)",
    goldZoneTitle: "สินทรัพย์ที่ดูแลแล้ว (โซนทอง)",
    sourceFiles: "ไฟล์ต้นฉบับ",
    statusSynced: "สถานะ: ซิงค์แล้ว",
    codeQualityAnalysis: "การวิเคราะห์คุณภาพโค้ด",
    issuesFound: "ปัญหาที่พบ",
    governanceChecks: "การตรวจสอบธรรมาภิบาล",
    securityPoliciesApplied: "ใช้นโยบายความปลอดภัยแล้ว",
    accessControl: "การควบคุมการเข้าถึง",
    leadDeveloper: "นักพัฒนาหลัก",
    juniorDeveloper: "นักพัฒนารุ่นเยาว์",
    qaEngineer: "วิศวกรประกันคุณภาพ",
    publishAsset: "เผยแพร่สินทรัพย์",
    refactoredCode: "โค้ดที่ปรับปรุงแล้ว",
    // Aether Canvas (Genesis Protocol)
    genesisProtocol: "โปรโตคอลเจเนซิส",
    voiceCommand: "คำสั่งเสียง",
    listening: "กำลังฟัง...",
    processing: "กำลังประมวลผล...",
    ready: "พร้อม",
    speakPrompt: "พูดคำสั่งเพื่อเริ่มการสร้าง...",
    finalize: "สิ้นสุด",
    saveImage: "บันทึกรูปภาพ",
    micError: "จำเป็นต้องได้รับอนุญาตให้ใช้ไมโครโฟนสำหรับคำสั่งเสียง",
    connectionError: "ไม่สามารถเชื่อมต่อกับจิตสำนึกแห่ง Aetherium ได้",
    exitGenesis: "ออกจากโปรโตคอลเจเนซิส",
    // Image Analysis
    imageAnalysis: "วิเคราะห์",
    uploadImage: "อัปโหลดรูปภาพ",
    analyze: "วิเคราะห์",
    analysisPlaceholder: "คุณต้องการทราบอะไรเกี่ยวกับภาพนี้",
    analysisResultTitle: "ผลการวิเคราะห์",
    dropOrClick: "วางรูปภาพที่นี่ หรือคลิกเพื่อเลือก",
    analyzing: "กำลังวิเคราะห์...",
    noImageUploaded: "กรุณาอัปโหลดรูปภาพเพื่อเริ่มการวิเคราะห์",
};
